version: '3'
services:
  database:
    image: postgres:12.10
    restart: always
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./db/data:/var/lib/postgresql/data
  metabase:
    platform: linux/x86_64
    image: metabase/metabase
    container_name: metabase
    restart: always
    mem_limit: 4GB
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: database
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - database
    volumes:
      - metabase_data:/metabase-data
    ports:
      - 3999:3000
volumes:
  db:
  metabase_data:
