version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      DATABASE_URL: postgres://postgres:password@database:5432/myapp
      JSON_RPC_URL: http://json-rpc-mock:8545
      MOCK_API_URL: http://mock-api:3002
    depends_on:
      - database
      - json-rpc-mock
      - mock-api

  database:
    image: postgres:12.10
    restart: always
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - ./db/data:/var/lib/postgresql/data

  json-rpc-mock:
    image: open-rpc/mock-server
    volumes:
      - ./test/mock-servers/json-rpc-mock:/data
    ports:
      - '8545:8545'
    environment:
      OPENRPC_MOCK_DATA_DIR: /data

  mock-api:
    image: mendhak/http-https-echo
    volumes:
      - ./test/mock-servers/mock-api:/data
    ports:
      - '3002:80'
    environment:
      MOCK_DATA_DIR: /data

volumes:
  db:
