/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKannaAuditScoreProvider,
  IKannaAuditScoreProviderInterface,
} from "../../../contracts/interfaces/IKannaAuditScoreProvider";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKannaAuditScoreProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IKannaAuditScoreProviderInterface {
    return new utils.Interface(_abi) as IKannaAuditScoreProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKannaAuditScoreProvider {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IKannaAuditScoreProvider;
  }
}
