export enum GrantType {
	ERC1271 = 'ERC1271',
	EIP4361 = 'EIP4361',
	AUTHORIZATION_CODE = 'AUTHORIZATION_CODE',
	REFRESH_TOKEN = 'REFRESH_TOKEN',
	CLIENT_CREDENTIALS = 'CLIENT_CREDENTIALS',
	PASSWORD = 'PASSWORD',
}
